---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-2
  labels:
    name: load-test-2
  namespace: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      name: load-test-2
  template:
    metadata:
      labels:
        name: load-test-2
    spec:
      containers:
      - name: load-test-2
        # image: nisaprmst/ta-load-test:3.0.0
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        args: ["-c", "locust --host http://34.124.201.179:30001 -f /config/locustfile.py --clients 1 --hatch-rate 1 --num-request 100000 --no-web"]
        # args: 
        # - -c 
        # - FLOOR=50; CEILING=100; RANGE=$(($CEILING-$FLOOR+1)); while true; do RESULT=$RANDOM; let "RESULT %= $RANGE"; RESULT=$(($RESULT+$FLOOR)); locust --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py --users 1500 --spawn-rate $RESULT --headless --run-time 3m; done
        # args: 
        # - -c 
        # - FLOOR=50; CEILING=200; RANGE=$(($CEILING-$FLOOR+1)); while true; do RESULT=$RANDOM; let "RESULT %= $RANGE"; RESULT=$(($RESULT+$FLOOR)); locust --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py --clients 1500 --hatch-rate $RESULT --num-request 300 --no-web; done

      nodeSelector:
        beta.kubernetes.io/os: linux
